- config/owasp/suppressions.xml
N/A
https://tools.hmcts.net/jira/browse/HMAN-23
Added temporary CVE suppressions to suppressions.xml to allow pipeline to complete.  These will be investigated later.
```
[ ] Yes
[x] No
```
> Add temporary CVE suppressions

- Dockerfile
- config/owasp/suppressions.xml
- src/functionalTest/java/uk/gov/hmcts/reform/hmc/hmi/befta/EmptySmokeTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/GetWelcomeTest.java
- src/main/java/uk/gov/hmcts/reform/hmc/controllers/RootController.java
- src/test/java/uk/gov/hmcts/reform/rsecheck/DemoUnitTest.java
https://tools.hmcts.net/jira/browse/HMAN-23
CFT Hearing Service - Create a repository for CFT microservice
```
[ ] Yes
[ ] No
```
> HMAN-23 Dummy commit

- README.md
> HMAN-23 code review comment

- infrastructure/state.tf
> HMAN-21 fix build

- src/main/resources/db/migration/V20211117_43__HMAN-43-unavailabilityType.sql
https://tools.hmcts.net/jira/browse/HMAN-43
add missing column
```
[ ] Yes
[X] No
```
> HMAN-43 add missing column unavailabilityType

- src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementControllerIT.java
- src/integrationTest/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceIT.java
- src/main/resources/db/migration/V20211208_22__HMAN-22-RelatedParty.sql
- src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/utils/TestingUtil.java
https://tools.hmcts.net/jira/browse/HMAN-22
Validate Schema for POST request
Related party is an optional field , Changing the code to reflect the same.
```
[ ] Yes
[ ] No
```
> HMAN-22 - Related Party bug

- src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementControllerIT.java
- src/main/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementController.java
- src/main/java/uk/gov/hmcts/reform/hmc/exceptions/ValidationError.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/DeleteHearingRequest.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/UpdateHearingRequest.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/UpdateRequestDetails.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementService.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementControllerTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/utils/TestingUtil.java
https://tools.hmcts.net/jira/browse/HMAN-37
```
[ ] Yes
[X] No
```
> HMAN-37: Validate Schema for PUT request

- src/main/resources/db/migration/V20211202_60__HMAN-60-HearingResponse.sql
https://tools.hmcts.net/jira/browse/HMAN-60
Update HMC Database model for hearing response tables 
```
[ ] Yes
[ ] No
```
> HMAN-60 - Hearing tables

- src/main/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementController.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementService.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImpl.java
https://tools.hmcts.net/jira/browse/HMAN-31
```
[ ] Yes
[X] No
```
> HMAN-31 remove test endpoints

- build.gradle
- config/owasp/suppressions.xml
> CVE-2021-27568 and removed suppression

- src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
https://tools.hmcts.net/jira/browse/HMAN-69
incorrect default hearing created status
```
[ ] Yes
[ ] No
```
> HMAN-69 - Fix Hearing Status bug

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2357
Updating the suppression date  1 month ahead
```
[ ] Yes
[X ] No
```
> Changed suppression date to 1 month ahead

- Jenkinsfile_CNP
- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/hmc/hmi/befta/CftHearingServiceTestAutomationAdapter.java
- src/functionalTest/java/uk/gov/hmcts/reform/hmc/hmi/befta/TestDataLoaderMain.java
- src/integrationTest/java/uk/gov/hmcts/reform/hmc/RestExceptionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/repository/DataStoreRepositoryTest.java
https://tools.hmcts.net/jira/browse/CCD-2451
Removing jcenter due to [shutdown](https://blog.gradle.org/jcenter-shutdown)
```
[ ] Yes
[ x] No
```
> Update to build.gradle

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2339
fix for CVE-2021-29425
```
[ ] Yes
[ x] No
```
> fix for CVE-2021-29425

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2592
Suppressing:
CVE-2021-22060, CVE-2022-23181, CVE-2021-42550, CVE-2021-43797, CVE-2021-44228, CVE-2021-44832, CVE-2021-45046, CVE-2021-45105
```
[ ] Yes
[ x] No
```
> CCD-2592: Suppress CVE pending investigation

- src/test/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementControllerTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceTest.java
> test tidy up 

- config/owasp/suppressions.xml
Also added dates if they do not have them
https://tools.hmcts.net/jira/browse/CCD-2497
Amended the CVE suppression date by a month
```
[ ] Yes
[ X] No
```
> Amend Suppression Date

- charts/hmc-cft-hearing-service/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-2579
```
[ ] Yes
[ ] No
```
> helm update

- charts/hmc-cft-hearing-service/Chart.yaml
> Upgrade to Latest Base Helm Charts

- src/main/java/uk/gov/hmcts/reform/hmc/ApplicationParams.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImpl.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceTest.java
> Make access control toggleable

- src/main/resources/application.yaml
> Correct authorised s2s list for initial audiences

- src/main/java/uk/gov/hmcts/reform/hmc/service/PartiesNotifiedServiceImpl.java
> fix master build

- charts/hmc-cft-hearing-service/Chart.yaml
- charts/hmc-cft-hearing-service/values.yaml
> Try adding sslmode

- src/main/java/uk/gov/hmcts/reform/hmc/data/HearingEntity.java
- src/main/java/uk/gov/hmcts/reform/hmc/validator/LinkedHearingValidator.java
- src/test/java/uk/gov/hmcts/reform/hmc/validator/LinkedHearingValidatorTest.java
https://tools.hmcts.net/jira/browse/HMAN-136
ignore date check if no hearing responses
```
[ ] Yes
[ ] No
```
> HMAN-136 ignore date check if no hearing responses

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2924
CVE-2022-22965
```
[ ] Yes
[ X] No
```
> Bump Spring Framework to 5.3.18

- src/main/java/uk/gov/hmcts/reform/hmc/helper/hmi/EntitySubTypeMapper.java
> HMAN-149 - Align entityClassCode values sent to LA

- src/integrationTest/resources/sql/update-case-hearing-request.sql
> Prevent PK issue when running single tests

- src/contractTest/java/uk/gov/hmcts/reform/hmc/BasePactTesting.java
- src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementControllerIT.java
- src/main/java/uk/gov/hmcts/reform/hmc/helper/ContactDetailMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingResponseMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/helper/hmi/CommunicationsMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/IndividualDetails.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/hmi/EntityCommunication.java
- src/test/java/uk/gov/hmcts/reform/hmc/helper/GetHearingResponseMapperTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/helper/hmi/CommunicationsMapperTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/utils/TestingUtil.java
https://tools.hmcts.net/jira/browse/HMAN-142
```
[x] Yes
[ ] No
```
> HMAN-142 - collection for hearingChannelEmail and hearingChannelPhone

- src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementControllerIT.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/UnavailabilityDow.java
- src/main/java/uk/gov/hmcts/reform/hmc/validator/CapitalizedCaseEnumPatternValidator.java
- src/main/java/uk/gov/hmcts/reform/hmc/validator/CapitalizedEnumPattern.java
- src/test/java/uk/gov/hmcts/reform/hmc/utils/TestingUtil.java
- src/test/java/uk/gov/hmcts/reform/hmc/validator/CapitalizedEnumPatternValidatorTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/validator/EnumPatternValidatorTest.java
https://tools.hmcts.net/jira/browse/HMAN-148
hearingDetails.partyDetails.unavailabilityDOW.DOW enum needs to be changed to accept the following only Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday as list assist does not accept all caps as valid value
```
[ ] Yes
[X] No
```
> HMAN-148 - Fail validation if UnavailabilityDow is not capitalized

- src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementControllerIT.java
- src/main/java/uk/gov/hmcts/reform/hmc/exceptions/ValidationError.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/PartyDetails.java
- src/main/resources/db/migration/V20220411_156__HMAN-156-ExtendPartyRoleCharacters.sql
- src/test/java/uk/gov/hmcts/reform/hmc/validator/BeanValidatorTest.java
[HMAN-156 - Change partyRole maxLength in the PUT/POST hearing request payload](https://tools.hmcts.net/jira/browse/HMAN-156)
Updated partyRole in the partyDetails to allow 40 characters
```
[ ] Yes
[x] No
```
> HMAN-156 updated partyRole to have 40 characters

- src/main/java/uk/gov/hmcts/reform/hmc/exceptions/ValidationError.java
- src/main/java/uk/gov/hmcts/reform/hmc/helper/hmi/HmiHearingResponseMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/HmcHearingUpdate.java
https://tools.hmcts.net/jira/browse/HMAN-143
add new fields to Topic on hearing_response from ListAssist
```
[ ] Yes
[x] No
```
> HMAN-143 - add new fields to Topic on hearing_response from ListAssist

- src/main/java/uk/gov/hmcts/reform/hmc/data/HearingPartyEntity.java
- src/main/java/uk/gov/hmcts/reform/hmc/data/PartyRelationshipDetailsEntity.java
- src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingResponseMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/helper/PartyRelationshipDetailsMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/repository/HearingPartyRepository.java
- src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/utils/TestingUtil.java
> Quick fix for entity mappings

- config/owasp/suppressions.xml
Suppresion for spring-core-5.3.18.jar relate dependency check failure.
```
[ ] Yes
[ x] No
```
> Spring-core-5.3.18 dependency issue suppression

- src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingActualsResponseMapper.java
> Add null check for actual hearings

- src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingResponseMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingsResponseMapper.java
https://tools.hmcts.net/jira/browse/HMAN-187
Handle when there are no panels available for GET /hearings
```
[ ] Yes
[x] No
```
> HMAN-187 - Handle when there are no panels available for GET /hearings

- src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
> HMAN-173 Update Constants.java

- src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/MessageProcessorIT.java
- src/main/java/uk/gov/hmcts/reform/hmc/client/hmi/HearingCode.java
- src/main/java/uk/gov/hmcts/reform/hmc/config/MessageProcessor.java
- src/main/java/uk/gov/hmcts/reform/hmc/domain/model/enums/HearingStatus.java
- src/main/java/uk/gov/hmcts/reform/hmc/helper/hmi/HmiHearingResponseMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/HmcHearingUpdate.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/InboundQueueService.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/InboundQueueServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/hmc/config/MessageProcessorTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/helper/HmiHearingResponseMapperTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/service/InboundQueueServiceTest.java
https://tools.hmcts.net/jira/browse/HMAN-185
https://tools.hmcts.net/jira/browse/HMAN-191
185 - issue with listener aborting when exception is thrown
191 - issue with retrieving listingCaseStatus for the topic
```
[ ] Yes
[X] No
```
> HMAN-185 and HMAN-191

- src/main/java/uk/gov/hmcts/reform/hmc/model/listassist/HearingGroup.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/LinkedHearingGroupServiceImpl.java
https://tools.hmcts.net/jira/browse/HMAN-195
```
[ ] Yes
[x] No
```
> HMAN-195 - Send LA labels for linkedHearingGroup groupLinkType

- build.gradle
- src/main/java/uk/gov/hmcts/reform/hmc/model/CaseCategory.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/HearingLocation.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/PanelPreference.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/PartyDetails.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/UnavailabilityDow.java
https://tools.hmcts.net/jira/browse/HMAN-165
Wherever we are using enums as strings in payloads that get published to Swagger, we should publish which values are actually accepted
```
[ ] Yes
[X] No
```
> HMAN-165 - Document enum values in swagger ui pages

- src/main/java/uk/gov/hmcts/reform/hmc/helper/HearingActualsMapper.java
https://tools.hmcts.net/jira/browse/HMAN-202
Handle null actual day parties
```
[ ] Yes
[x] No
```
> HMAN-202 - Handle null actual day parties

- src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementControllerIT.java
- src/integrationTest/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceIT.java
- src/main/java/uk/gov/hmcts/reform/hmc/exceptions/ValidationError.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/HearingDetails.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/utils/TestingUtil.java
https://tools.hmcts.net/jira/browse/HMAN-179
[put /hearing] optional amendReasonCode field required by ListAssist
```
[ ] Yes
[ ] No
```
> HMAN-179 [put /hearing] optional amendReasonCode field required by ListAssist

- src/main/java/uk/gov/hmcts/reform/hmc/helper/hmi/HmiHearingResponseMapper.java
- src/main/resources/db/migration/V20220505_198__HMAN-198-Alter_Hearing_Attendee_Details_Column.sql
- src/test/java/uk/gov/hmcts/reform/hmc/helper/HmiHearingResponseMapperTest.java
https://tools.hmcts.net/jira/browse/HMAN-198
HMC moves hearingRequest into EXCEPTION state if optional fields not provided
```
[ ] Yes
[ ] No
```
> HMAN-198 HMC moves hearingRequest into EXCEPTION state if optional fields not provided

- src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingActualsResponseMapper.java
- src/test/java/uk/gov/hmcts/reform/hmc/utils/TestingUtil.java
imports missing from master in Class
GetHearingActualsResponseMapper
TestingUtils
```
[ ] Yes
[ x ] No
```
> master-fix imports added

- src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HearingActualsManagementControllerIT.java
- src/main/java/uk/gov/hmcts/reform/hmc/data/ActualHearingPartyEntity.java
- src/main/java/uk/gov/hmcts/reform/hmc/data/HearingPartyEntity.java
- src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingActualsResponseMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingResponseMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/helper/HearingActualsMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/helper/IndividualDetailMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/helper/PartyDetailMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/hearingactuals/ActualDayParty.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/hearingactuals/Party.java
- src/test/java/uk/gov/hmcts/reform/hmc/helper/GetHearingActualsResponseMapperTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/helper/IndividualDetailMapperTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/utils/TestingUtil.java
https://tools.hmcts.net/jira/browse/HMAN-203
GET /hearingActuals/ the individualDetails is an ARRAY not a single obj
Changed Individual details mapping to 1-1 from Hearing Party instead of 1-many
```
[ ] Yes
[ ] No
```
> HMAN-203 changed GET /hearingActuals/ the individualDetails to a single object

- src/main/java/uk/gov/hmcts/reform/hmc/exceptions/ValidationError.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceTest.java
[Remove checks for empty arrays where fields are optional](https://tools.hmcts.net/jira/browse/HMAN-213)
Remove checks for empty arrays where fields are optional
```
[ ] Yes
[x] No
```
> HMAN-213 - Remove checks for empty arrays where fields are optional

- src/main/java/uk/gov/hmcts/reform/hmc/model/partiesnotified/PartiesNotifiedResponses.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/PartiesNotifiedServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/hmc/controllers/PartiesNotifiedControllerTest.java
> HMAN-219 - Make hearingID string for GET /partiesNotified

- src/main/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementController.java
> Don't check access control for GET /hearing if the request is for isValid

- Jenkinsfile_nightly
- build.gradle
- config/fortify-client.properties
https://tools.hmcts.net/jira/browse/HMAN-211
Add Fortify checks to nightly pipeline
```
[ ] Yes
[x] No
```
> HMAN-211 - Add Fortify checks to nightly pipeline

- src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HearingActualsManagementControllerIT.java
- src/main/java/uk/gov/hmcts/reform/hmc/data/HearingResponseEntity.java
> HMAN-262 - Delete orphans on PUT /hearingActuals

- charts/hmc-cft-hearing-service/Chart.yaml
- charts/hmc-cft-hearing-service/values.yaml
> Use same connection string secret from vault for all

- src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
- src/main/java/uk/gov/hmcts/reform/hmc/helper/hmi/HmiSubmitHearingRequestMapper.java
- src/test/java/uk/gov/hmcts/reform/hmc/helper/hmi/HmiSubmitHearingRequestMapperTest.java
https://tools.hmcts.net/jira/browse/HMAN-274
```
[ ] Yes
[ x] No
```
> HMAN-274 Update List Assist Standard Amendment Reason

- src/main/java/uk/gov/hmcts/reform/hmc/helper/hmi/HmiDeleteHearingRequestMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/hmi/CancellationReason.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/hmi/HmiDeleteHearingRequest.java
- src/test/java/uk/gov/hmcts/reform/hmc/helper/hmi/HmiDeleteHearingRequestMapperTest.java
> HMAN-317: Send correct object to LA for cancellations

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/HMAN-329
```
[ ] Yes
[ ] No
```
> Temporary suppression of CVE-2022-34305

- charts/hmc-cft-hearing-service/Chart.yaml
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3561
Upgrade Java and Node JS versions in chart for all the respective repos
```
[ ] Yes
[x] No
```
> Ccd 3561 master 2

- src/main/java/uk/gov/hmcts/reform/hmc/helper/hmi/ListingMapper.java
- src/test/java/uk/gov/hmcts/reform/hmc/helper/hmi/ListingMapperTest.java
https://tools.hmcts.net/jira/browse/HMAN-376
Do not sent listingLanguage field if language is English
```
[ ] Yes
[x] No
```
> HMAN-376 Do not send listingLanguage field if language is NOT Welsh

- src/main/java/uk/gov/hmcts/reform/hmc/helper/hmi/ListingMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/hmi/Listing.java
- src/test/java/uk/gov/hmcts/reform/hmc/helper/hmi/ListingMapperTest.java
https://tools.hmcts.net/jira/browse/HMAN-372
In the payload update where room attribute values are mapped - change from roomAttributes to listingRoomAttributes
```
[ ] Yes
[x] No
```
> HMAN-372 Update roomAttribute to listingRoomAttributes

- src/main/java/uk/gov/hmcts/reform/hmc/helper/hmi/HmiHearingResponseMapper.java
- src/test/java/uk/gov/hmcts/reform/hmc/helper/HmiHearingResponseMapperTest.java
https://tools.hmcts.net/jira/browse/HMAN-374
https://tools.hmcts.net/jira/browse/HMAN-377
```
[ ] Yes
[x] No
```
> HMAN-377/374 - Handle both LISTED and CANCEL statuses for cancel scenarios

- config/owasp/suppressions.xml
HMAN-392 (https://tools.hmcts.net/jira/browse/HMAN-392)
Updated suppressions file to temporarily suppress CVE-2022-31197.
```
[ ] Yes
[x] No
```
> HMAN-392: Temporarily suppress CVE-2022-31197

- src/functionalTest/resources/features/F-003 GET Hearing/S-003.1.td.json
- src/main/java/uk/gov/hmcts/reform/hmc/client/hmi/ListingReasonCode.java
- src/main/java/uk/gov/hmcts/reform/hmc/helper/CaseHearingRequestMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/helper/HearingDetailsMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/HearingDetails.java
- src/main/java/uk/gov/hmcts/reform/hmc/validator/ListingReasonCodeEnumPatternValidator.java
- src/test/java/uk/gov/hmcts/reform/hmc/helper/CaseCreateHearingRequestMapperTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/helper/CaseHearingRequestMapperTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/helper/GetHearingResponseMapperTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/utils/TestingUtil.java
https://tools.hmcts.net/jira/browse/HMAN-400
```
[ ] Yes
[x] No
```
> HMAN-400 - Only allow no-mapping-available for listingAutoChangeReasonCode

- src/main/java/uk/gov/hmcts/reform/hmc/client/hmi/ListingReasonCode.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/HearingDetails.java
https://tools.hmcts.net/jira/browse/HMAN-410
Support `user-added-comments` for `listingAutoChangeReasonCode`
```
[ ] Yes
[x] No
```
> HMAN-410 - Support `user-added-comments` for `listingAutoChangeReasonCode`

- src/contractTest/java/uk/gov/hmcts/reform/hmc/utility/HearingResponsePactUtil.java
- src/integrationTest/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceIT.java
- src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingResponseCommonCode.java
- src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingResponseMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingsResponseMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/HearingDaySchedule.java
- src/test/java/uk/gov/hmcts/reform/hmc/helper/GetHearingResponseMapperTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/helper/GetHearingsResponseMapperTest.java
https://tools.hmcts.net/jira/browse/HMAN-405
https://tools.hmcts.net/jira/browse/HMAN-407
return multiple hearingDayPanels instead of the first one
```
[ ] Yes
[ ] No
```
> HMAN-405 HMAN-407 update logic for returning HearingDayPanel info

- infrastructure/main.tf
- infrastructure/variables.tf
> Create replica DB in ITHC

- infrastructure/main.tf
Reverts the temporary hmcts/hmc-cft-hearing-service#302 (only needed for testing terraform apply)
> Revert "Create replica DB in ITHC"

- infrastructure/aat.tfvars
- infrastructure/main.tf
- infrastructure/prod.tfvars
- infrastructure/variables.tf
> Create DB replicas in AAT and Prod

- config/owasp/suppressions.xml
- infrastructure/perftest.tfvars
- infrastructure/prod.tfvars
> Increase DB size in prod/perftest

- config/owasp/suppressions.xml
- infrastructure/perftest.tfvars
- infrastructure/prod.tfvars
Reverts hmcts/hmc-cft-hearing-service#307
> Revert "Increase DB size in prod/perftest"

- config/owasp/suppressions.xml
Suppression of CVE's
CVE-2022-38751 
CVE-2022-38750 
CVE-2022-38749
CVE-2022-38752
CVE-2022-42003
CVE-2022-42004
https://tools.hmcts.net/jira/browse/HMAN-423
https://tools.hmcts.net/jira/browse/HMAN-432
https://tools.hmcts.net/jira/browse/HMAN-438
CVE-2022-38751 CVE-2022-38750 CVE-2022-38749 hmc repos
CVE-2022-38752 - hmc-cft-hearing-service
CVE-2022-42003 and CVE-2022-42004 - hmc-cft-hearing-service
```
[ ] Yes
[ ] No
```
> HMAN-423, HMAN-432, HMAN-438 CVE suppressions.

- infrastructure/perftest.tfvars
- infrastructure/prod.tfvars
https://tools.hmcts.net/jira/browse/HMAN-437
Scale up DB to 4 vcores
```
[ ] Yes
[x] No
```
> HMAN-437 - Scale up DB

- config/owasp/suppressions.xml
- src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/MessageProcessorIT.java
- src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/MessageSenderToTopicConfigurationIT.java
- src/main/java/uk/gov/hmcts/reform/hmc/config/MessageProcessor.java
- src/main/java/uk/gov/hmcts/reform/hmc/config/MessageSenderToQueueConfiguration.java
- src/main/java/uk/gov/hmcts/reform/hmc/config/MessageSenderToTopicConfiguration.java
- src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/InboundQueueServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/service/InboundQueueServiceTest.java
HMAN-441: Monitor failures with the Hearing Service
[HMAN-441] (https://tools.hmcts.net/jira/browse/HMAN-441).
>    HMAN-441: Monitor failures with the Hearing Service

- src/main/resources/application.yaml
> HMAN-477 - Whitelist PRL

- build.gradle
- config/owasp/suppressions.xml
- src/integrationTest/java/uk/gov/hmcts/reform/hmc/BaseTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/hmc/wiremock/extensions/DynamicOAuthJwkSetResponseTransformer.java
- src/integrationTest/resources/wiremock-stubs/oauth-jwk-set.json
- src/main/java/uk/gov/hmcts/reform/hmc/config/SecurityConfiguration.java
- src/test/java/uk/gov/hmcts/reform/hmc/utils/KeyGenerator.java
https://tools.hmcts.net/jira/browse/HMAN-455
https://tools.hmcts.net/jira/browse/HMAN-454
Fix for snakeyaml - CVE-2022-41854
Fix for Tomcat - CVE-2022-42252
Fix for  Spring Security - CVE-2022-31690, CVE-2022-31692
- Removed deprecated WebSecurityConfigurerAdapter in [SecurityConfiguration.java](https://github.com/hmcts/hmc-cft-hearing-service/pull/325/files#diff-69a193a5467808675c35026ebbf06bfb8727dd2476f406110a5056356fd8483a)
```
[ ] Yes
[ x] No
```
> HMAN-455,HMAN-454: Tomcat and Spring Security 

- build.gradle
- charts/hmc-cft-hearing-service/Chart.yaml
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/HMAN-248
https://tools.hmcts.net/jira/browse/HMAN-392
https://tools.hmcts.net/jira/browse/HMAN-415
Fix hmc-cft-hearing-service CVEs.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
> Fix hmc-cft-hearing-service CVEs

- .github/workflows/dependency-check.yml
- .gitignore
- build.gradle
- config/owasp/suppressions.xml
- gradle/suppress.gradle
https://tools.hmcts.net/jira/browse/HMAN-494
Add suppressCves task
```
[ ] Yes
[ ] No
```
> HMAN-494 Auto suppress CVE

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/HMAN-501
Update suppressions.xml
```
[ ] Yes
[X] No
```
> HMAN-501: Update suppressions.xml

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/HMAN-507
Updated Apache Tomcat to 9.0.69 and moved temporary suppressions to false positives
```
[ ] Yes
[X] No
```
> HMAN-507 : updated Apache Tomcat to 9.0.69 and moved temporary suppressions to false positives

- build.gradle
- src/integrationTest/java/uk/gov/hmcts/reform/hmc/service/LinkedHearingGroupServiceIT.java
- src/main/java/uk/gov/hmcts/reform/hmc/exceptions/FhBadRequestException.java
- src/main/java/uk/gov/hmcts/reform/hmc/exceptions/RestExceptionHandler.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/LinkedHearingGroupServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/hmc/service/LinkHearingGroupServiceTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/service/LinkedHearingGroupServiceTest.java
update processing in error scenarios for linkedHearings Create, Amend and Delete endpoints
```
[ ] Yes
[ ] No
```
> HMAN-511, HMAN-512, HMAN-513 update linked Hearing endpoints

- charts/hmc-cft-hearing-service/Chart.yaml
https://tools.hmcts.net/jira/browse/HMAN-518
Upgrade base charts
```
[ ] Yes
[X] No
```
> HMAN-518 Upgrade base charts

- src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/MessageProcessorIT.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/InboundQueueServiceImpl.java
> HMAN-XXX update logging statement

- charts/hmc-cft-hearing-service/Chart.yaml
https://tools.hmcts.net/jira/browse/HMAN-533
HMAN-533-Fix-master-chart-jav-bump
```
[ ] Yes
[X] No
```
> HMAN-533-Fix-master-chart-jav-bump

- Dockerfile
https://tools.hmcts.net/jira/browse/HMAN-534
HMAN-534 : updated java image in Dockerfile
```
[ ] Yes
[X] No
```
> HMAN-534 : updated java image in Dockerfile

- src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingResponseMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/hmi/HearingResponse.java
- src/test/java/uk/gov/hmcts/reform/hmc/helper/GetHearingResponseMapperTest.java
https://tools.hmcts.net/jira/browse/HMAN-540
Add in hearingResponse.requestVersion
```
[ ] Yes
[ ] No
```
> HMAN-540- GET /hearing response - Add in hearingResponse.requestVersion

- Jenkinsfile_CNP
- build.gradle
- charts/hmc-cft-hearing-service/Chart.yaml
- charts/hmc-cft-hearing-service/values.preview.template.yaml
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/HMAN-558
HMAN-558 : Fix-CVE-2023-20862-CVE-2023-20863 (bumped versions of springframework and springsecurity)
```
[ ] Yes
[X] No
```
> HMAN-558 : Fix-CVE-2023-20862-CVE-2023-20863 (bumped versions of springframework and springsecurity)

- Jenkinsfile_CNP
- charts/hmc-cft-hearing-service/Chart.yaml
- charts/hmc-cft-hearing-service/values.preview.template.yaml
- src/integrationTest/java/uk/gov/hmcts/reform/hmc/repository/HearingResponseRepositoryIT.java
- src/integrationTest/resources/sql/unNotified-hearings-request.sql
- src/main/java/uk/gov/hmcts/reform/hmc/repository/HearingResponseRepository.java
https://tools.hmcts.net/jira/browse/HMAN-564
GET UnnotifiedHearings Endpoint returning Duplicates
```
[ ] Yes
[ ] No
```
> HMAN-564- Return distinct hearings

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/HearingManagementServiceImpl.java
https://tools.hmcts.net/jira/browse/HMAN-573
Terminal State - Ignore List Assist
```
[ ] Yes
[ ] No
```
> HMAN-573- Terminal State - Ignore List Assist

- src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
https://tools.hmcts.net/jira/browse/HMAN-586
review dynatrace logging statements
```
[ ] Yes
[ ] No
```
> HMAN-586- Review dynatrace logging statements

- infrastructure/main.tf
Updated the subnet_suffix attribute in the PostgreSQL module to point to the expanded subnet circumventing previous limitation. 
```
[ ] Yes
[x] No
```
> Subnet suffix update

- build.gradle
- src/main/java/uk/gov/hmcts/reform/hmc/helper/HearingActualsMapper.java
- src/test/java/uk/gov/hmcts/reform/hmc/helper/HearingActualsMapperTest.java
https://tools.hmcts.net/jira/browse/HMAN-590
Civil Duplicate Party participants in Hearings problem
```
[ ] Yes
[ ] No
```
> HMAN-590 fix Civil Duplicate Party participants in Hearings problem

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4771
bumped jackson.version, removed suppression
```
[ ] Yes
[X] No
```
> CCD-4771 : Fix CVE-2023-3511

- src/main/resources/room-attributes.json
…able
https://tools.hmcts.net/jira/browse/COT-672
Map "Type C" equipment Facility Code in HMC Room Attributes Table
```
[ ] Yes
[ ] No
```
> COT-672 Map "Type C" equipment Facility Code in HMC Room Attributes Table

- build.gradle
- config/owasp/suppressions.xml
- src/integrationTest/resources/wiremock-stubs/role-assignments.json
CCD-4736
bumped spring-boot to 2.7.18
```
[ ] Yes
[X] No
```
> CCD-4736: FIX-CVE-2023-20883

- build.gradle
- config/checkstyle/checkstyle.xml
- config/owasp/suppressions.xml
- gradle/wrapper/gradle-wrapper.properties
- src/functionalTest/resources/features/F-000/S-000.td.json
- src/functionalTest/resources/features/F-001 POST Hearing/S-001.1-get-hearing.td.json
- src/functionalTest/resources/features/F-001 POST Hearing/S-001.1.td.json
- src/functionalTest/resources/features/F-001 POST Hearing/S-001.2.td.json
- src/functionalTest/resources/features/F-001 POST Hearing/S-001.3.td.json
- src/functionalTest/resources/features/F-002 DELETE Hearing/S-002.1-get-hearing.td.json
- src/functionalTest/resources/features/F-002 DELETE Hearing/S-002.1.td.json
- src/functionalTest/resources/features/F-005 GET Hearings/S-005.1.td.json
- src/functionalTest/resources/features/F-005 GET Hearings/S-005.2.td.json
- src/functionalTest/resources/features/common/hmc/amendHearing/PutHEaringRequestBase.td.json
- src/functionalTest/resources/features/common/hmc/createHearing/CreateHearingRequest.td.json
- src/functionalTest/resources/features/common/hmc/deleteHearing/deleteHearingRequestBase.td.json
- src/functionalTest/resources/features/common/hmc/getHearing/GetHearingRequestBase.td.json
- src/integrationTest/resources/wiremock-stubs/role-assignments.json
- src/main/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementController.java
- src/test/java/uk/gov/hmcts/reform/hmc/controllers/PartiesNotifiedControllerTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/validator/CapitalizedEnumPatternValidatorTest.java
https://tools.hmcts.net/jira/browse/HMAN-608
<cve>CVE-2023-28709</cve>
<cve>CVE-2023-20873</cve>
<cve>CVE-2023-41080</cve>
<cve>CVE-2023-4586</cve>
<cve>CVE-2023-42794</cve>
<cve>CVE-2023-42795</cve>
<cve>CVE-2023-45648</cve>
<cve>CVE-2023-45960</cve>
<cve>CVE-2023-46589</cve>
<cve>CVE-2023-6378</cve>
```
[ ] Yes
[ ] No
```
> HMAN-608: Spring 2.5

- src/integrationTest/java/uk/gov/hmcts/reform/hmc/RestExceptionHandlerTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementControllerIT.java
- src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
- src/main/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementController.java
- src/main/java/uk/gov/hmcts/reform/hmc/exceptions/ValidationError.java
https://tools.hmcts.net/jira/browse/HMAN-618
https://tools.hmcts.net/jira/browse/HMAN-620
Change deployment id mandatory to optional
Ensure deployment id length is not greater than 40 characters
```
[ ] Yes
[ ] No
```
> Deployment id changes

- src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
https://tools.hmcts.net/jira/browse/HMAN-631
Rename hmcts-deployment-id to hmctsDeploymentId
```
[ ] Yes
[ ] No
```
> HMAN-631- Rename hmcts-deployment-id to hmctsDeploymentId

- infrastructure/perftest.tfvars
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-5167
Upgrade current V15 perftest V4 to V8 cores
```
[ ] Yes
[x] No
```
> Upgrade current V15 perftest V4 to V8 cores

- src/main/resources/db/migration/V20240129_572__HMAN-572-PendingRequests.sql
https://tools.hmcts.net/jira/browse/HMAN-572
Create Pending_Requests Table
```
[ ] Yes
[ ] No
```
> HMAN-572 Create Pending_Requests Table

- infrastructure/perftest.tfvars
> Update perftest to 16 CPU

- src/main/resources/db/migration/V20240223_580__HMAN-580-Alter_Table_Hearing_LastGoodStatusField.sql
https://tools.hmcts.net/jira/browse/HMAN-580
```
[ ] Yes
[ ] No
```
> HMAN 580 last good status field - hearing table

- infrastructure/aat.tfvars
- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-5139
AAT Infrastructure changes for V15 replica
> AAT Infrastructure changes for V15 replica

- infrastructure/aat.tfvars
- infrastructure/import.tf
- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/CCD-5139
Appending replica db name
> Appending replica db name

- infrastructure/prod.tfvars
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=1382&projectKey=CCD&view=detail&selectedIssue=CCD-5163
Adding config for the creation of a V15 replica against the source V15 prod flexible D/B
> Adding replica config for V15 prod

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/HMAN-677
Fix CVE-2024-1597
```
[ ] Yes
[x] No
```
> HMAN-677 fix CVE-2024-1597

- src/main/resources/db/migration/V20240613_837__HMAN-837-update_room_id_field_length.sql
https://tools.hmcts.net/jira/browse/HMAN-837
```
[ ] Yes
[ ] No
```
> HMAN-837 update room id field length

- build.gradle
> fix fortify gradle task

- UnNotifiedHearings/WithEndDateTime.sql
- UnNotifiedHearings/WithoutEndDateTime.sql
Query to UnNotified Hearings - Services onboarding
https://tools.hmcts.net/jira/browse/HMAN-642
```
[ ] Yes
[ ] No
```
> HMAN-642 UnNotified Hearings

- infrastructure/variables.tf
> Remove references to cnp-module-postgres

- infrastructure/output.tf
- infrastructure/prod.tfvars
- infrastructure/variables.tf
> tidy-up-v11

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- src/main/resources/db/migration/V20240213_578__HMAN-578-CreateHearingStatusAudit.sql
- src/main/resources/db/migration/V20240402_638__HMAN-638-CreateLinkedHearingStatusAudit.sql
- src/main/resources/db/migration/V20240429_578__HMAN-578-Alter_Table_Hearing_StatusAudit.sql
> Docker limit

- src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/MessageProcessorIT.java
- src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/InboundQueueServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/hmc/service/InboundQueueServiceTest.java
https://tools.hmcts.net/jira/browse/HMAN-560
Add extra logger info statements when hearing is updated to Exception
```
[ ] Yes
[ ] No
```
> HMAN-560 Add case ref, service code when hearing updates to exception

- src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/MessageProcessorIT.java
- src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/InboundQueueServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/hmc/service/InboundQueueServiceTest.java
https://tools.hmcts.net/jira/browse/HMAN-871
Add error description to logger
```
[ ] Yes
[ ] No
```
> HMAN-871- Add error description

- build.gradle
- src/main/java/uk/gov/hmcts/reform/hmc/config/MessageProcessor.java
- src/main/java/uk/gov/hmcts/reform/hmc/config/MessageSenderToQueueConfiguration.java
- src/main/java/uk/gov/hmcts/reform/hmc/config/MessageSenderToTopicConfiguration.java
- src/main/java/uk/gov/hmcts/reform/hmc/config/QueueClientConfig.java
- src/main/java/uk/gov/hmcts/reform/hmc/constants/Constants.java
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/HMAN-873
Azure connectivity issues
```
[ ] Yes
[ ] No
```
> HMAN-873-Azure connectivity issues

- .gitignore
- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/hmc/hmi/befta/CftHearingServiceBeftaRunner.java
- src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/RestTemplateConfigurationTest.java
- src/integrationTest/java/uk/gov/hmcts/reform/hmc/config/SwaggerPublisherTest.java
- src/main/java/uk/gov/hmcts/reform/hmc/config/SecurityConfiguration.java
- src/main/java/uk/gov/hmcts/reform/hmc/config/SwaggerConfiguration.java
- src/main/java/uk/gov/hmcts/reform/hmc/controllers/HearingActualsController.java
- src/main/java/uk/gov/hmcts/reform/hmc/controllers/HearingActualsManagementController.java
- src/main/java/uk/gov/hmcts/reform/hmc/controllers/HearingManagementController.java
- src/main/java/uk/gov/hmcts/reform/hmc/controllers/LinkHearingGroupController.java
- src/main/java/uk/gov/hmcts/reform/hmc/controllers/LinkedHearingGroupController.java
- src/main/java/uk/gov/hmcts/reform/hmc/controllers/PartiesNotifiedController.java
- src/main/java/uk/gov/hmcts/reform/hmc/controllers/UnNotifiedHearingsController.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/CaseCategory.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/HearingDetails.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/HearingLocation.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/PanelPreference.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/PartyDetails.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/UnavailabilityDow.java
- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/CME-192
```
[ ] Yes
[ ] No
```
> CME-192: migrate springfox to spring doc

- config/owasp/suppressions.xml
> tidy up on suppressions

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CME-128
```
[ ] Yes
[ ] No
```
> CME-362: do not sync ithc

- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CME-128
```
[ ] Yes
[ ] No
```
> Cme-362 test

- src/integrationTest/java/uk/gov/hmcts/reform/hmc/repository/HearingResponseRepositoryIT.java
- src/integrationTest/java/uk/gov/hmcts/reform/hmc/service/UnNotifiedHearingServiceIT.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/PartiesNotifiedServiceImpl.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/UnNotifiedHearingServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/hmc/PartiesNotifiedCommonGeneration.java
- src/test/java/uk/gov/hmcts/reform/hmc/service/PartiesNotifiedServiceTest.java
- src/test/java/uk/gov/hmcts/reform/hmc/service/UnNotifiedHearingServiceTest.java
https://tools.hmcts.net/jira/browse/HMAN-862
sort the order of hearing in PartiesNotified Endpoints
```
[ ] Yes
[ ] No
```
> HMAN-862- CR-96 sort PartiesNotified Endpoints

- src/integrationTest/java/uk/gov/hmcts/reform/hmc/controllers/LinkHearingGroupControllerIT.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/LinkedHearingGroupService.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/LinkedHearingGroupServiceImpl.java
- src/test/java/uk/gov/hmcts/reform/hmc/service/LinkedHearingGroupServiceTest.java
https://tools.hmcts.net/jira/browse/HMAN-867
hearing - order by linkedOrder, sub ordered by hearingID descending
```
[ ] Yes
[x] No
```
> HMAN-867 Added required sort order

- infrastructure/main.tf
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CME-128
```
[ ] Yes
[ ] No
```
> CME-128: DB monitoring

- build.gradle
https://tools.hmcts.net/jira/browse/HMAN-896
upgrade rse-cft-lib' version '0.19.1568' to address Java toolchain issue with bootWithCCD
```
[ ] Yes
[ ] No
```
> HMAN-896 update cft-lib to address the java tool chain problem

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/HMAN-938
400 Errors on hmc-cft-hearing-service-perftest - During CAFCASS Perf Testing
```
[ ] Yes
[ ] No
```
> HMAN-938 : Add http-header-size to yaml

- charts/hmc-cft-hearing-service/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-6193
```
[ ] Yes
[ ] No
```
> CCD-6193 update base chart versions

- src/main/java/uk/gov/hmcts/reform/hmc/controllers/LinkHearingGroupController.java
https://tools.hmcts.net/jira/browse/HMAN-943
Update controller method name
```
[ ] Yes
[X] No
```
> HMAN-943 Update controller method name

- src/main/java/uk/gov/hmcts/reform/hmc/helper/GetHearingActualsResponseMapper.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/hearingactuals/Party.java
- src/test/java/uk/gov/hmcts/reform/hmc/helper/GetHearingActualsResponseMapperTest.java
https://tools.hmcts.net/jira/browse/HMAN-561
Add 'partyType' field to /hearingsActuals (GET) - response
```
[ ] Yes
[ ] No
```
> HMAN-561 : Add 'partyType' field to /hearingsActuals (GET) - response

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6280
https://tools.hmcts.net/jira/browse/CCD-6285
https://tools.hmcts.net/jira/browse/CCD-6278
https://tools.hmcts.net/jira/browse/CCD-6283
https://tools.hmcts.net/jira/browse/CCD-6279
```
[ ] Yes
[X] No
```
> Ccd 6280 suppress CVE 2024 38286

- infrastructure/state.tf
NA
bump azurerm
```
[ ] Yes
[X] No
```
> Update state.tf bump azurerm

- infrastructure/import.tf
- infrastructure/main.tf
DTSPO-25342
Importing platops user group as auth can't be added directly to the replica server.
> DTSPO-25342 - import PlatOps group

- infrastructure/main.tf
- infrastructure/state.tf
https://tools.hmcts.net/jira/browse/CME-229
```
[ ] Yes
[ ] No
```
> CME-229: Update azurerm and AD

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6362
Suppression
```
[ ] Yes
[X] No
```
> CCD-6362 :: Update suppressions.xml

- infrastructure/import.tf
Reverts hmcts/hmc-cft-hearing-service#571
> Revert "DTSPO-25342 - import PlatOps group"

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6374
```
[ ] Yes
[ ] No
```
> Suppression CVE-2024-24549, CVE-2024-23672

- Jenkinsfile_CNP
https://tools.hmcts.net/jira/browse/CME-367
```
[ ] Yes
[ ] No
```
> CME-367: REenable ithc sync

- build.gradle
- config/owasp/suppressions.xml
- settings.gradle
https://tools.hmcts.net/jira/browse/CME-509
```
[ ] Yes
[ ] No
```
> CME-509: replace jitpack with azure

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CME-631
```
[ ] Yes
[ x] No
```
> Fix CVE-2023-52428

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6621
CCD-6621 :: Suppress CVEs
```
[ ] Yes
[X] No
```
> CCD-6621 :: Suppress CVEs

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6636
Suppressed CVE
```
[ ] Yes
[X] No
```
> CCD-6636 :: Update suppressions.xml

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6796
CCD-6796 :: Add suppressions
```
[ ] Yes
[X] No
```
> CCD-6796 :: Add suppressions

- infrastructure/import.tf
- infrastructure/main.tf
https://tools.hmcts.net/jira/browse/DTSPO-27699
Added import block for pgsql_adadmin
```
[ ] Yes
[X] No
```
> Added import block for pgsql_adadmin

- src/functionalTest/resources/features/F-002 DELETE Hearing/F-002.feature
- src/functionalTest/resources/features/F-003 GET Hearing/F-003.feature
- src/functionalTest/resources/features/F-004 PUT Hearing/F-004.feature
- src/functionalTest/resources/features/F-005 GET Hearings/F-005.feature
> Rebecca patch1

- infrastructure/state.tf
NA
updated value
```
[ ] Yes
[X] No
```
> Fix TF error in master - Update state.tf
